"""
ITR-5 Document Parser
=====================
Extracts structured financial data from ITR-5.docx (Income Tax Return Form 5)
for LLPs / Firms. Parses Part A-BS (Balance Sheet), Part A-Trading Account,
and Part A-P&L (Profit & Loss) tables.

The ITR-5 docx generated by the IT department portal uses wide merged-cell tables.
Values are found at specific column indices within each table:
  - Part A-BS (Table 7):  sub-items at col14, totals at col16
  - Part A-Trading (Table 9): sub-items at col7, totals at col9
  - Part A-P&L (Table 10): sub-items at col15, totals at col29

This module provides a single entry point: parse_itr5(filepath) which returns
a flat dictionary of extracted amounts keyed by schedule references.
"""

import os
import re
import docx

DATA_DIR = r"C:\Users\hp\Desktop\CA\DATA"
ITR5_FILE = os.path.join(DATA_DIR, "ITR-5.docx")


def _parse_indian_number(text):
    """Convert an Indian-style comma-separated number string to float.
    
    Examples:
        '54,87,35,423' -> 548735423.0
        '25,00,000' -> 2500000.0
        'NIL' -> 0.0
        '' -> None
    """
    if not text:
        return None
    text = text.strip()
    if text.upper() == 'NIL' or text == '-' or text == '':
        return 0.0
    # Remove commas and try to parse
    cleaned = text.replace(',', '')
    try:
        return float(cleaned)
    except ValueError:
        return None


def _get_cell_value(row, col_index):
    """Safely get cell text from a row at a given column index."""
    try:
        cells = row.cells
        if col_index < len(cells):
            return cells[col_index].text.strip().replace('\n', ' ')
    except (IndexError, AttributeError):
        pass
    return ''


def _find_amount_in_row(row, preferred_cols, fallback_scan=True):
    """Extract a numeric value from a row (list of strings or docx row)."""
    if hasattr(row, 'cells'):
        cells = [c.text.strip().replace('\n', ' ') for c in row.cells]
    elif isinstance(row, (list, tuple)):
        cells = row
    else:
        return None
    
    # Try preferred columns first
    for col in preferred_cols:
        if col < len(cells):
            text = cells[col]
            val = _parse_indian_number(text)
            if val is not None:
                return val
    
    # Fallback: scan right-to-left for any recognizable number
    if fallback_scan:
        for i in range(len(cells) - 1, -1, -1):
            text = cells[i]
            if re.match(r'^[\d,]+$', text) and len(text) > 2:
                val = _parse_indian_number(text)
                if val is not None:
                    return val
            elif text.upper() == 'NIL':
                return 0.0
    
    return None


def _match_label(row, keywords, max_cols=8):
    """Check if any of the first max_cols cells contain all of the keywords."""
    if hasattr(row, 'cells'):
        cells = [c.text.strip().replace('\n', ' ') for c in row.cells]
    elif isinstance(row, (list, tuple)):
        cells = row
    else:
        return False
    
    if isinstance(keywords, str):
        keywords = [keywords]
    for i in range(min(max_cols, len(cells))):
        text = cells[i].lower()
        if all(kw.lower() in text for kw in keywords):
            return True
    return False


def _extract_table_data(table):
    """Pre-extracts table rows into pure Python lists of cell strings for blazing fast searches."""
    return [[c.text.strip().replace('\n', ' ') for c in row.cells] for row in table.rows]


def _find_row_by_label(table_or_data, keywords, start_row=0, max_cols=8):
    """Find the first row matching keyword(s)."""
    if isinstance(table_or_data, (list, tuple)):
        rows = table_or_data
    else:
        rows = _extract_table_data(table_or_data)
    
    for r_idx in range(start_row, len(rows)):
        if _match_label(rows[r_idx], keywords, max_cols):
            return r_idx, rows[r_idx]
    return None, None


def parse_audited_financials(xlsx_path):
    """Parse Audited_Financials.xlsx and extract Current Year Balance Sheet and P&L data."""
    if not xlsx_path or not os.path.exists(xlsx_path):
        return {}
    try:
        import openpyxl
        wb = openpyxl.load_workbook(xlsx_path, data_only=True, read_only=True)
        res = {}
        if 'BS' in wb.sheetnames:
            ws = wb['BS']
            for row in ws.iter_rows(values_only=True):
                if not any(row): continue
                label = str(row[0] or '').strip().lower()
                nums = [c for c in row if isinstance(c, (int, float))]
                val = nums[-2] if len(nums) >= 2 else (nums[-1] if len(nums) == 1 else None)
                if val is not None:
                    if 'share capital' in label: res['share_capital'] = val
                    elif 'reserves and surplus' in label: res['reserves_surplus'] = val
                    elif 'long-term borrowings' in label: res['lt_borrowings'] = val
                    elif 'short-term borrowings' in label: res['st_borrowings'] = val
                    elif 'micro enterprises' in label: res['trade_payables_msme'] = val
                    elif 'other than' in label and 'micro' in label: res['trade_payables_others'] = val
                    elif 'other current liabilities' in label: res['other_current_liabilities'] = val
                    elif 'short-term provisions' in label: res['st_provisions'] = val
                    elif 'property, plant and equipment' in label and 'ppe_net' not in res: res['ppe_net'] = val
                    elif 'current investment' in label: res['current_investments'] = val
                    elif 'inventories' in label: res['inventories'] = val
                    elif 'cash and cash equivalents' in label: res['cash_bank'] = val
                    elif 'short term loans and advances' in label: res['st_loans_advances'] = val
                    elif 'other current assets' in label: res['other_current_assets'] = val
                    elif 'deferred tax assets' in label: res['deferred_tax_assets'] = val

        if 'PL' in wb.sheetnames:
            ws = wb['PL']
            for row in ws.iter_rows(values_only=True):
                if not any(row): continue
                label = str(row[0] or '').strip().lower()
                nums = [c for c in row if isinstance(c, (int, float))]
                val = nums[-2] if len(nums) >= 2 else (nums[-1] if len(nums) == 1 else None)
                if val is not None:
                    if 'revenue from operations' in label: res['revenue_operations'] = val
                    elif 'other income' in label: res['other_income'] = val
                    elif 'cost of construction' in label: res['cost_construction'] = val
                    elif 'changes in inventories' in label: res['change_inventories'] = val
                    elif 'employee benefits' in label: res['employee_benefits'] = val
                    elif 'finance cost' in label: res['finance_cost'] = val
                    elif 'depreciation and amortization' in label: res['depreciation'] = val
                    elif 'other expenses' in label and 'total' not in label: res['other_expenses'] = val
                    elif 'profit before tax' in label: res['pbt'] = val
        return res
    except Exception as e:
        print(f"Error parsing audited financials: {e}")
        return {}


def _find_table_by_heading(doc, title_keywords, exclude_keywords=None):
    """Find a table by checking the text in its first row."""
    if isinstance(title_keywords, str):
        title_keywords = [title_keywords]
    if isinstance(exclude_keywords, str):
        exclude_keywords = [exclude_keywords]
        
    for idx, table in enumerate(doc.tables):
        if len(table.rows) == 0:
            continue
        first_row_text = " ".join([c.text.strip().lower() for c in table.rows[0].cells])
        matches = all(k.lower() in first_row_text for k in title_keywords)
        if matches:
            if exclude_keywords and any(ex.lower() in first_row_text for ex in exclude_keywords):
                continue
            return idx, table
    return None, None


_ITR5_CACHE = {}

def clear_itr5_cache():
    """Clears in-memory ITR5 cache."""
    _ITR5_CACHE.clear()

def parse_itr5(filepath=None):
    """Parse the ITR docx (ITR-5 or ITR-6) and extract key financial schedule data with mtime caching."""
    if filepath is None:
        filepath = ITR5_FILE
    
    if not os.path.exists(filepath):
        print(f"ITR file not found at: {filepath}")
        return None
    
    try:
        mtime = os.path.getmtime(filepath)
        cache_key = (os.path.abspath(filepath), mtime)
        if cache_key in _ITR5_CACHE:
            return _ITR5_CACHE[cache_key].copy()
    except Exception:
        cache_key = None
    
    try:
        doc = docx.Document(filepath)
    except Exception as e:
        print(f"Error opening ITR document: {e}")
        return None
    
    if len(doc.tables) < 5:
        print(f"ITR document has only {len(doc.tables)} tables")
        return None
    
    result = {}
    
    # 1. Locate BS Table (excluding Ind AS)
    bs_idx, bs_table_obj = _find_table_by_heading(doc, ["part a", "bs"], ["ind as", "ind-as"])
    if bs_table_obj is None and len(doc.tables) > 6:
        bs_table_obj = doc.tables[6]

    if bs_table_obj:
        bs_rows = _extract_table_data(bs_table_obj)
        for r_idx, row in enumerate(bs_rows):
            row_txt = " ".join(row).lower()
            cells = row
            # extract rightmost valid currency amount from cells
            num = None
            for c in cells:
                if ',' in c:
                    n = _parse_indian_number(c)
                    if n is not None:
                        num = n
                        break
            if num is None:
                for c in reversed(cells):
                    n = _parse_indian_number(c)
                    if n is not None and (n > 100 or n == 0.0):
                        num = n
                        break
            
            if num is not None:
                if 'partners' in row_txt and 'capital' in row_txt and 'total' not in row_txt:
                    result['partners_capital'] = num
                elif 'total partners' in row_txt:
                    result['total_partners_fund'] = num
                elif 'issued, subscribed' in row_txt:
                    result['share_capital'] = num
                elif 'general reserve' in row_txt:
                    result['general_reserve'] = num
                elif 'total shareholder' in row_txt:
                    result['total_shareholder_fund'] = num
                elif 'from others' in row_txt and ('b2' in row_txt or 'rupee loans' in row_txt or 'term loans' in row_txt or 'long-term' in row_txt):
                    if 'lt_borrowings' not in result:
                        result['secured_loans_others'] = num
                        result['lt_borrowings'] = num
                elif 'from banks' in row_txt and 'rupee loans' in row_txt:
                    result['secured_loans_banks'] = num
                elif 'total short-term borrowings' in row_txt or 'total short term borrowings' in row_txt:
                    result['st_borrowings'] = num
                elif 'total trade payables' in row_txt or '4b' in row_txt and 'trade payables' in row_txt:
                    result['total_sundry_creditors'] = num
                    result['trade_payables_total'] = num
                elif 'total short-term provisions' in row_txt or 'total short term provisions' in row_txt:
                    result['other_provisions'] = num
                    result['st_provisions'] = num
                elif 'net block' in row_txt and 'fixed_assets_net_block' not in result:
                    result['fixed_assets_net_block'] = num
                elif 'capital work-in-progress' in row_txt:
                    result['cwip'] = num
                elif 'total fixed assets' in row_txt:
                    result['total_fixed_assets'] = num
                elif 'total current investments' in row_txt:
                    result['current_investments'] = num
                elif 'total investments' in row_txt:
                    result['total_investments'] = num
                elif 'total inventories' in row_txt:
                    result['total_inventories'] = num
                elif 'total cash and cash equivalents' in row_txt or 'total cash & cash' in row_txt:
                    result['total_cash_bank'] = num
                elif 'total short-term loans and advances' in row_txt:
                    result['st_loans_advances'] = num
                elif 'other current assets' in row_txt and 'total' not in row_txt:
                    result['other_current_assets'] = num

    # 2. Locate Trading Table
    tr_idx, tr_table_obj = _find_table_by_heading(doc, ["trading"], ["ind as", "ind-as"])
    if tr_table_obj:
        tr_rows = _extract_table_data(tr_table_obj)
        for r_idx, row in enumerate(tr_rows):
            row_txt = " ".join(row).lower()
            num = None
            for c in row:
                if ',' in c:
                    n = _parse_indian_number(c)
                    if n is not None:
                        num = n
                        break
            if num is None:
                for c in reversed(row):
                    n = _parse_indian_number(c)
                    if n is not None and (n > 100 or n == 0.0):
                        num = n
                        break
            if num is not None:
                if 'revenue from operations' in row_txt or '4d' in row_txt:
                    if 'revenue_from_operations' not in result:
                        result['revenue_from_operations'] = num
                elif 'direct expenses' in row_txt and ('total' in row_txt or '9' in row_txt):
                    if 'direct_expenses' not in result:
                        result['direct_expenses'] = num
                elif 'closing stock' in row_txt:
                    result['closing_stock_trading'] = num
                elif 'gross profit' in row_txt:
                    result['gross_profit_trading'] = num

    # 3. Locate P&L Table
    pl_idx, pl_table_obj = _find_table_by_heading(doc, ["p & l"], ["ind as", "ind-as"])
    if pl_table_obj is None:
        pl_idx, pl_table_obj = _find_table_by_heading(doc, ["profit and loss"], ["ind as", "ind-as"])
        
    if pl_table_obj:
        pl_rows = _extract_table_data(pl_table_obj)
        for r_idx, row in enumerate(pl_rows):
            unique = []
            for c in row:
                if not unique or c != unique[-1]:
                    unique.append(c)
            row_start = unique[0].lower() if unique else ''
            row_joined = ' '.join(unique).lower()
            num = None
            for c in unique:
                if ',' in c:
                    n = _parse_indian_number(c)
                    if n is not None:
                        num = n
                        break
            if num is None:
                for c in reversed(unique):
                    n = _parse_indian_number(c)
                    if n is not None and (n > 100 or n == 0.0):
                        num = n
                        break
            if num is not None:
                if '14xii' in unique and row_start in ('xii', ''):
                    result['total_other_income'] = num
                elif '22xi' in unique and row_start in ('xi', ''):
                    result['total_compensation_employees'] = num
                elif 'repairs to machinery' in row_joined:
                    result['repairs_machinery'] = num
                elif '51iii' in unique and 'total (i + ii)' in row_joined:
                    result['finance_cost_total'] = num
                elif '52' in unique and row_start.startswith('depreciation'):
                    result['depreciation_pl'] = num
                elif '53' in unique and row_start.startswith('net profit before taxes'):
                    result['net_profit_before_tax'] = num
                elif '56' in unique and row_start.startswith('profit after tax'):
                    result['profit_after_tax'] = num

    # Derived values if missing
    if "finance_cost_total" not in result:
        loan_int = result.get("interest_on_loan_trading", 0) or 0
        od_int = result.get("interest_on_od_trading", 0) or 0
        result["finance_cost_total"] = loan_int + od_int
    
    if "employee_benefit_trading" not in result:
        salary_dir = result.get("salary_direct_trading", 0) or 0
        bonus = result.get("employee_bonus_trading", 0) or 0
        result["employee_benefit_trading"] = salary_dir + bonus
        
    if cache_key:
        _ITR5_CACHE[cache_key] = result.copy()
    
    return result


def get_itr5_summary(data=None):
    """Get a human-readable summary of parsed ITR-5 data."""
    if data is None:
        data = parse_itr5()
    if data is None:
        return "ITR-5 data could not be parsed."
    
    def _fmt(val):
        if val is None:
            return f"{'N/A':>18s}"
        try:
            return f"{val:>18,.0f}"
        except (ValueError, TypeError):
            return f"{str(val):>18s}"
            
    lines = [
        "ITR-5 Parsed Data Summary",
        "=" * 50,
        "",
        "--- BALANCE SHEET (Part A-BS) ---",
        f"Partners' Capital:        {_fmt(data.get('partners_capital'))}",
        f"Total Partners' Fund:     {_fmt(data.get('total_partners_fund'))}",
        f"Secured Loans (Banks):    {_fmt(data.get('secured_loans_banks'))}",
        f"Secured Loans (Others):   {_fmt(data.get('secured_loans_others'))}",
        f"Total Loan Funds:         {_fmt(data.get('total_loan_funds'))}",
        f"Total Sources:            {_fmt(data.get('total_sources_of_funds'))}",
        f"Fixed Assets Net Block:   {_fmt(data.get('fixed_assets_net_block'))}",
        f"Total Investments:        {_fmt(data.get('total_investments'))}",
        f"Total Inventories:        {_fmt(data.get('total_inventories'))}",
        f"Total Sundry Debtors:     {_fmt(data.get('total_sundry_debtors'))}",
        f"Total Cash & Bank:        {_fmt(data.get('total_cash_bank'))}",
        f"Other Current Assets:     {_fmt(data.get('other_current_assets'))}",
        f"Advances Recoverable:     {_fmt(data.get('advances_recoverable'))}",
        f"Deposits/Loans/Adv:       {_fmt(data.get('deposits_loans_advances'))}",
        f"Sundry Creditors:         {_fmt(data.get('total_sundry_creditors'))}",
        f"Other Payables:           {_fmt(data.get('other_payables'))}",
        f"Other Provisions:         {_fmt(data.get('other_provisions'))}",
        f"Total Appln of Funds:     {_fmt(data.get('total_application_of_funds'))}",
        "",
        "--- TRADING ACCOUNT ---",
        f"Revenue from Operations:  {_fmt(data.get('revenue_from_operations'))}",
        f"Direct Expenses:          {_fmt(data.get('direct_expenses'))}",
        f"Gross Profit:             {_fmt(data.get('gross_profit_trading'))}",
        "",
        "--- PROFIT & LOSS ---",
        f"Total Other Income:       {_fmt(data.get('total_other_income'))}",
        f"Total Compensation:       {_fmt(data.get('total_compensation_employees'))}",
        f"Depreciation:             {_fmt(data.get('depreciation_pl'))}",
        f"Net Profit Before Tax:    {_fmt(data.get('net_profit_before_tax'))}",
        f"Profit After Tax:         {_fmt(data.get('profit_after_tax'))}",
    ]
    
    return "\n".join(lines)


if __name__ == "__main__":
    import sys
    sys.stdout.reconfigure(encoding='utf-8')
    data = parse_itr5()
    if data:
        print(get_itr5_summary(data))
        print(f"\n\nTotal keys extracted: {len(data)}")
    else:
        print("Failed to parse ITR-5.")
